### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by martinosorb** [oscarmorrison/zoteroRemarkable#1]
Apologies for contacing you like this. Your code didn't work for me, perhaps due to different Zotero versions. I've created my own fork, which is also more pythonically written and has an installation tool with more detailed instructions. Would you mind adding a licence to your work so I can know if I can distribute my fork?
Thanks

**Comment by oscarmorrison** [comment]
Yes @martinosorb absolutely. 
Glad this was able to help (I hope) in some way. Keen to see what you have, done. You are welcome to commit it to this and help maintain if that is more useful?

**Comment by rogelioamancisidor** [comment]
@martinosorb Which version of zotero do you have?

**Comment by oscarmorrison** [comment]
5.0.85

**Comment by martinosorb** [comment]
Mine is 5.0.89 (on Mac)

**Comment by rogelioamancisidor** [comment]
what about your Remarkable version? 1 or the new model 2?

**Comment by martinosorb** [comment]
I have model 1, I believe the new version isn't out yet.
